---
title: "Assignment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('tidyverse')
library('caret')

raw_dat = ISLR::Auto %>%
  as_tibble() 

dat = raw_dat %>%
  select(acceleration, weight)
```

```{r}
raw_dat %>%
  ggplot(aes(x = weight, y = acceleration)) +
  geom_point()
```


Complete the following steps:  

  - Preprocess your data by one of the following (your choice): scale, center, standardize, normalize
  - Decide on an appropriate value of K ... via trial and error
  - Visualize your results in a plot
```{r}
# Scale data
scaled_func = preProcess(dat, method = c("scale"))
scaled_dat = predict(scaled_func, dat)
scaled_dat
```

```{r}
# Check that scaling worked on a couple colums - SD should be 1.
scaled_dat %>%
  summarize(
    mean_mpg = mean(weight),
    sd_mpg = sd(weight),
    mean_cylinders = mean(acceleration),
    sd_cylinders = sd(acceleration))
```

```{r}
# Check distributions for a couple columns
sd1 = scaled_dat %>%
  ggplot(aes(x = weight)) +
  geom_density()

sd2 = scaled_dat %>%
  ggplot(aes(x = acceleration)) +
  geom_density()

gridExtra::grid.arrange(sd1, sd2)
```


```{r}
# Use k-means to find clusters in scaled raw_data
result1 = kmeans(scaled_dat, 2)
p1 = scaled_dat %>%
  mutate(cluster = result1$cluster) %>%
  ggplot(aes(x = weight, y = acceleration, col = as.factor(cluster))) + 
  geom_point()

result2 = kmeans(scaled_dat, 3)
p2 = scaled_dat %>%
  mutate(cluster = result2$cluster) %>%
  ggplot(aes(x = weight, y = acceleration, col = as.factor(cluster))) + 
  geom_point()

result3 = kmeans(scaled_dat, 4)
p3 = scaled_dat %>%
  mutate(cluster = result3$cluster) %>%
  ggplot(aes(x = weight, y = acceleration, col = as.factor(cluster))) + 
  geom_point()

result4 = kmeans(scaled_dat, 5)
p4 = scaled_dat %>%
  mutate(cluster = result4$cluster) %>%
  ggplot(aes(x = weight, y = acceleration, col = as.factor(cluster))) + 
  geom_point()

gridExtra::grid.arrange(p1, p2, p3, p4, ncol = 2)
```

